"""Searches for a pattern within a DNA sequence and 
returns a list with the locations where the pattern occurs"""
def patternSearch(DNA, pattern):
	locations = []
	for i in range(len(DNA)-len(pattern) + 1):
		DNA_slice = DNA[i:i+len(pattern)]
		if DNA_slice == pattern:
			locations.append(i+1)
	return locations
	
print (patternSearch("TCTATCGTTCTATCGTCTCTATCGCACTCTATCGGGGATCTATCGTTCTCGGCTATCTATCGTATCTATCGGACTCTATCGTTCTATCGTTTATCTATCGCATTCTATCGCCTCTATCGTGTATCTATCGAGTTTCTATCGCAATGTAGTCTATCGTCTATCGATCTATCGTCTATCGGTCTATCGCTCTATCGTTATTCTATCGCTCTATCGGTGCGAGTTCTATCGGTCTATCGTCTATCGTCTATCGGCACTTGGCGGCATCTATCGCTCTATCGTCTATCGTGTCTATCGTCTATCGTCTATCGTACTCTATCGGTCTATCGTCTATCGATCTATCGCTCTATCGGTCTATCGACCTCTATCGATAAATCTATCGTCTATCGTGGACTTCTATCGGAGTCTATCGTCTATCGAGCCCTCCAGTCTATCGTGTCTATCGAATTTCGCGTCTATCGACGTCTATCGTCTATCGTCTATCGCTTATCTATCGCATCTATCGATTCTATCGATCTATCGATCTATCGGGTCTATCGGATATCTATCGTCTATCGCCACCGTTCTATCGCAACTCTAGCAACTCTCTATCGGATCTATCGGATCTATCGTCTATCGGTCTATCGGGTGACATTTTGCGAAGAGCAGCACAGGAGTCTATCGATTCTCTATCGGTCTATCGAACTCTATCGTCTATCGTCACGTCTATCGAGATCTATCGTCTATCGGGTTTCTATCGCTCTATCGAATCTATCGGATGACTCTATCGTAAGCTCTATCGAACAATCTATCGTCTATCGTAATCTATCGTCTATCGTCTATCGGATTCTATCGTGATCTATCGTCTATCGTATCTATCGTCTATCGTAAGGTTCTATCGCTCTATCGTCTATCGCACTTCTATCGG", "TCTATCGTC"))

#Solution:
#[9, 150, 165, 230, 237, 272, 288, 295, 320, 373, 403, 462, 469, 541, 602, 683, 690, 712, 784, 801, 808, 835, 851, 879]
